'use server';
/**
 * @fileOverview A Genkit flow for administrators to generate engaging and descriptive text for various content types.
 *
 * - adminContentGenerator - A function that generates content based on provided details.
 * - AdminContentGeneratorInput - The input type for the adminContentGenerator function.
 * - AdminContentGeneratorOutput - The return type for the adminContentGenerator function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const AdminContentGeneratorInputSchema = z.discriminatedUnion('contentType', [
  z.object({
    contentType: z.literal('foodMenuItem'),
    itemName: z.string().describe('Name of the food menu item.'),
    ingredients: z.string().describe('Key ingredients of the food item.'),
    cuisine: z.string().describe('Cuisine type (e.g., Italian, Mexican).'),
    price: z.string().optional().describe('Optional: Price of the food item.'),
    dietaryRestrictions: z
      .string()
      .optional()
      .describe('Optional: Any dietary restrictions or notes (e.g., vegetarian, gluten-free).'),
  }),
  z.object({
    contentType: z.literal('laundryService'),
    serviceName: z.string().describe('Name of the laundry service.'),
    descriptionOfProcess: z.string().describe('Brief description of how the service works.'),
    garmentTypesHandled: z
      .string()
      .describe('Types of garments the service handles (e.g., delicates, dry cleaning).'),
    priceRange: z.string().optional().describe('Optional: Price range for the laundry service.'),
    turnaroundTime: z
      .string()
      .optional()
      .describe('Optional: Estimated turnaround time for the service.'),
  }),
  z.object({
    contentType: z.literal('eCommerceProduct'),
    productName: z.string().describe('Name of the e-commerce product.'),
    features: z.string().describe('Key features of the product.'),
    benefits: z.string().describe('Benefits users will get from the product.'),
    category: z.string().describe('Category of the product (e.g., electronics, apparel).'),
    price: z.string().optional().describe('Optional: Price of the product.'),
    brand: z.string().optional().describe('Optional: Brand of the product.'),
  }),
  z.object({
    contentType: z.literal('crowdfundingCampaign'),
    campaignTitle: z.string().describe('Title of the crowdfunding campaign.'),
    goal: z.string().describe('Financial goal of the campaign.'),
    briefDescription: z.string().describe('Brief description of the campaign purpose.'),
    targetAudience: z.string().describe('Who is this campaign targeting?'),
    impact: z.string().optional().describe('Optional: The potential impact of the campaign.'),
  }),
]);
export type AdminContentGeneratorInput = z.infer<typeof AdminContentGeneratorInputSchema>;

const AdminContentGeneratorOutputSchema = z.object({
  generatedContent: z.string().describe('The engaging and descriptive text generated by the AI.'),
});
export type AdminContentGeneratorOutput = z.infer<typeof AdminContentGeneratorOutputSchema>;

export async function adminContentGenerator(
  input: AdminContentGeneratorInput
): Promise<AdminContentGeneratorOutput> {
  try {
    return await adminContentGeneratorFlow(input);
  } catch (error) {
    console.error("Admin Content Generator Error:", error);
    // Generic fallback for administrative tasks
    return {
      generatedContent: "Experience premium quality and seamless fulfillment with our latest platform offering. Designed for the modern Nigerian lifestyle."
    };
  }
}

const prompt = ai.definePrompt({
  name: 'adminContentGeneratorPrompt',
  input: { schema: AdminContentGeneratorInputSchema },
  output: { schema: AdminContentGeneratorOutputSchema },
  prompt: `You are an expert copywriter and marketing specialist tasked with creating engaging and descriptive content for various platform listings.
Your goal is to generate compelling text that attracts users and clearly communicates the value or details of the item/service.

Here are the details for the content you need to generate:

{{#eq contentType "foodMenuItem"}}
  Content Type: Food Menu Item
  Item Name: {{{itemName}}}
  Ingredients: {{{ingredients}}}
  Cuisine: {{{cuisine}}}
  {{#if price}}Price: {{{price}}}{{/if}}
  {{#if dietaryRestrictions}}Dietary Restrictions: {{{dietaryRestrictions}}}{{/if}}
  Please generate an engaging and delicious-sounding description for this menu item, highlighting its flavors and unique qualities.
{{/eq}}

{{#eq contentType "laundryService"}}
  Content Type: Laundry Service
  Service Name: {{{serviceName}}}
  Description of Process: {{{descriptionOfProcess}}}
  Garment Types Handled: {{{garmentTypesHandled}}}
  {{#if priceRange}}Price Range: {{{priceRange}}}{{/if}}
  {{#if turnaroundTime}}Turnaround Time: {{{turnaroundTime}}}{{/if}}
  Please generate a clear, trustworthy, and appealing description for this laundry service, emphasizing convenience and quality.
{{/eq}}

{{#eq contentType "eCommerceProduct"}}
  Content Type: E-commerce Product
  Product Name: {{{productName}}}
  Features: {{{features}}}
  Benefits: {{{benefits}}}
  Category: {{{category}}}
  {{#if price}}Price: {{{price}}}{{/if}}
  {{#if brand}}Brand: {{{brand}}}{{/if}}
  Please generate a persuasive and informative description for this e-commerce product, focusing on its features, benefits, and how it meets customer needs.
{{/eq}}

{{#eq contentType "crowdfundingCampaign"}}
  Content Type: Crowdfunding Campaign
  Campaign Title: {{{campaignTitle}}}
  Goal: {{{goal}}}
  Brief Description: {{{briefDescription}}}
  Target Audience: {{{targetAudience}}}
  {{#if impact}}Potential Impact: {{{impact}}}{{/if}}
  Please generate an inspiring and clear description for this crowdfunding campaign, encouraging contributions by highlighting its purpose and potential impact.
{{/eq}}
`,
});

const adminContentGeneratorFlow = ai.defineFlow(
  {
    name: 'adminContentGeneratorFlow',
    inputSchema: AdminContentGeneratorInputSchema,
    outputSchema: AdminContentGeneratorOutputSchema,
  },
  async (input) => {
    console.log('[adminContentGeneratorFlow] Input:', JSON.stringify(input, null, 2));
    const { output } = await prompt(input);
    console.log('[adminContentGeneratorFlow] Output:', JSON.stringify(output, null, 2));
    return output!;
  }
);
